### ISSUE TITLE
Crear pantalla deslizante

### ISSUE THREAD

**Issue by nahue02** [unlam-tec-movil/A2-2023-H1-News-Feed#14]
La idea es crear tres pantallas que se puedan ver al deslizar el dedo hacia el costado.
Las pantallas serían:
1. Pantalla principal (Lista de noticias).
2. Filtro de categorías.
3. Lista de favoritos.

**Comment by TiernoFacundo** [comment]
ya se creo el Bottom Navigation para navegar a través de las 3 pantallas. Cierro issue.
